name: check code form build and test

on:
  push:
    branches:
      - feature/*
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
        - uses: actions/checkout@v2
    
        - name: Set up Python 3.11
          uses: actions/setup-python@v2
          with: 
            python-version: 3.11
    
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
    
        #- name: Run tests
        #  run: pytest
    
        - name: Check code style
          run: ruff check --config ruff.toml
    
        - name: Check code formatting
          run: ruff format --config ruff.toml

        #- name: Check code typings
        #  run: |
        #    cd app
        #    mypy .